services:
  - name: "minio/minio"
    command: ["server", "/data"]


variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  MINIO_ACCESS_KEY: "access_key"
  MINIO_SECRET_KEY: "secret_key"
  MINIO_LOCAL_URL: "http://minio__minio:9000"


cache:
  key: $CI_PROJECT_NAME
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/target"

#include:
#  - project: 'infra/ci-cd/base'
#    file: '.gitlab-ci.yml'
#
#  - project: 'infra/ci-cd/tests'
#    file: '.gitlab-ci.yml'


test:
  stage: pre-test
  image: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"
  script:
    - sbt clean test

releaseSnapshot:
  stage: deploy
  only:
    - develop
  image: "hseeberger/scala-sbt:8u212_1.2.8_2.13.0"
  script:
    - sbt clean "release with-defaults"